#spring.application.name=EcommerceAPI

spring:
  application:
    name: EcommerceAPI

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: ${URL_DB:jdbc:postgresql://localhost:5432/ecommerce_db?currentSchema=public}
    username: ${USERNAME_DB:admin}
    password: ${PASSWORD_DB:admin}
    driverClassName: org.postgresql.Driver

server:
  port: 8080